title: A Programmer's Dream
name: A Programmer's Dream
author: Stephen Wrighton
email: stephen@wrighton.org
description: > # this means to ignore newlines until "baseurl:"
  Yet more Geek ruminations to clutter up the internets.
about: >
    Yet more Geek ruminations to clutter up the internets
 
master_repo: false
baseurl:
url: "https://programmer.wrighton.org"
markdown: kramdown
highlighter: rouge

SocialDefaultLogo: tcardbase.png

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4
future: false


rtl: false
owner:
  name:           "Stephen Wrighton"
  avatar:         "https://programmer.wrighton.org/images/avatar2019.jpg"
  email:          "stephen@wrighton.org"
  # Social networking links used in footer. Update and remove as you like.
  twitter: kidananubix
  github: https://github.com/sswrighton
  stackoverflow: https://stackoverflow.com/users/7516/stephen-wrighton
  linkedin: https://www.linkedin.com/in/sswrighton
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-1739066-2
google_adsense: ca-pub-3572508565773804

show_excerpts: true # set to false to remove excerpts on the homepage

# Where are tags and categories displayed
tag_page: '/tags/'
