title: A Programmer's Dream
author: sswrighton
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet more Geek ruminations to clutter up the internets.
about: >
    Programming life


master_repo: false
url: "http://vinitkumar.me/white-paper"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4


rtl: false
owner:
  name:           whitepaper
  avatar:         "https://www.gravatar.com/avatar/53a4066fb888b4a54fa1e650945e34a8?s=64&d=identicon&r=PG"
  email:          "sswrighton@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: sswrighton
  github: https://github.com/sswrighton
  stackexchange: https://stackoverflow.com/users/7516/stephen-wrighton
  linkedin: https://www.linkedin.com/in/sswrighton
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-1739066-2

show_excerpts: true # set to false to remove excerpts on the homepage


