title: A Programmer's Dream
author: sswrighton
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet more Geek ruminations to clutter up the internets.

# social links
twitter_username: kidananubix
github_username:  sswrighton

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
